### ISSUE TITLE
Reject invalid or closed aliases at Postfix

### ISSUE THREAD

**Issue by olineham** [fyiorgnz/alaveteli#9] opened 2018-10-16 07:50 UTC
Currently postfix checks email aliases match a regex, but not exact hashes. Rejecting invalid aliases at SMTP time would eliminate a lot of spam from holding_pen and also give authorities immediate feedback when they've mistyped an address.

Downside: some authorities seem to do a lot of manual copying of addresses between systems, which is where typos arise. They may give up instead of dealing with the hard bounce.

**Comment by nigeljonez** [comment] 2019-02-07 10:12
PR #6 has a DB view as part of SES enablement - where we need to ensure that we don't backscatter for reputation.

fyiorgnz/docker-postfix#4 is the counter-part issue for image changes required for postfix.

**Comment by nigeljonez** [comment] 2019-07-21 00:09
Closing this issue as it's effectively a duplicate of fyiorgnz/docker-postfix#4 and that'll hopefully get done as part of the postfix image improvements for fyi-next+1

**Closed by nigeljonez** 2019-07-21 00:09 UTC
Labels: inbound-email
